=== Criticaldex/L2JLivingWorld/game/data/xsd/teleporterData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="npc" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="npcs" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="npc" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute type="xs:int" name="id" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="teleport" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="location" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute type="xs:string" name="name" use="optional" />
												<xs:attribute type="xs:int" name="x" use="required" />
												<xs:attribute type="xs:int" name="y" use="required" />
												<xs:attribute type="xs:short" name="z" use="required" />
												<xs:attribute type="xs:int" name="feeId" use="optional" />
												<xs:attribute type="xs:int" name="feeCount" use="optional" />
												<xs:attribute name="castleId" use="optional">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:pattern value="\d+(;\d+)*" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="optional" />
									<xs:attribute name="type">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="NORMAL" />
												<xs:enumeration value="HUNTING" />
												<xs:enumeration value="NOBLES_TOKEN" />
												<xs:enumeration value="NOBLES_ADENA" />
												<xs:enumeration value="OTHER" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:integer" name="id" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Criticaldex/L2JLivingWorld/game/data/teleporters/clanhall/Gludio/35386.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/teleporterData.xsd">
	<npc id="35386"> <!-- Boyer -->
		<teleport name="tel1" type="OTHER">
			<location name="Village Square" x="-14393" y="123671" z="-3144" />
			<location name="East Gate Entrance" x="-11817" y="123652" z="-3079" />
			<location name="West Gate Entrance" x="-16796" y="124108" z="-3127" />
			<location name="South Gate Entrance" x="-14207" y="126547" z="-3151" />
			<location name="North Gate Entrance" x="-14591" y="121024" z="-2990" />
		</teleport>
		<teleport name="tel2" type="OTHER">
			<location name="Village Square" x="-14393" y="123671" z="-3144" />
			<location name="East Gate Entrance" x="-11817" y="123652" z="-3079" />
			<location name="West Gate Entrance" x="-16796" y="124108" z="-3127" />
			<location name="South Gate Entrance" x="-14207" y="126547" z="-3151" />
			<location name="North Gate Entrance" x="-14591" y="121024" z="-2990" />
			<location name="Ruins of Agony" x="-41248" y="122848" z="-2912" feeCount="500" />
			<location name="Ruins of Despair" x="-19359" y="136846" z="-3760" feeCount="500" />
			<location name="Ant Nest" x="-9959" y="176184" z="-4160" feeCount="500" />
			<location name="Windawood Manor" x="-28327" y="155125" z="-3496" feeCount="500" castleId="1" />
		</teleport>
	</npc>
</list>

=== Criticaldex/L2JLivingWorld/game/data/teleporters/clanhall/Goddard/35605.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/teleporterData.xsd">
	<npc id="35605"> <!-- Angout -->
		<teleport name="tel1" type="OTHER">
			<location name="Village Square" x="147728" y="-56331" z="-2776" />
			<location name="North Gate Entrance" x="147731" y="-58930" z="-2976" />
			<location name="East Gate Entrance" x="150561" y="-57489" z="-2976" />
			<location name="West Gate Entrance" x="144866" y="-57464" z="-2976" />
		</teleport>
		<teleport name="tel2" type="OTHER">
			<location name="Village Square" x="147728" y="-56331" z="-2776" />
			<location name="North Gate Entrance" x="147731" y="-58930" z="-2976" />
			<location name="East Gate Entrance" x="150561" y="-57489" z="-2976" />
			<location name="West Gate Entrance" x="144866" y="-57464" z="-2976" />
			<location name="Varka Silenos Barracks" x="125740" y="-40864" z="-3736" feeCount="500" />
			<location name="Ketra Orc Outpost" x="146990" y="-67128" z="-3640" feeCount="500" />
			<location name="Entrance to the Forge of the Gods" x="169018" y="-116303" z="-2432" feeCount="500" />
			<location name="Wall of Argos" x="165054" y="-47861" z="-3560" feeCount="500" />
			<location name="Hot Springs" x="144880" y="-113468" z="-2560" feeCount="500" />
		</teleport>
	</npc>
</list>

=== Criticaldex/L2JLivingWorld/game/data/teleporters/town/30320.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/teleporterData.xsd">
	<npc id="30320"> <!-- Richlin -->
		<teleport type="NORMAL">
			<location name="The Town of Gludio" x="-12694" y="122776" z="-3114" feeCount="7300" castleId="1" />
			<location name="Talking Island Village" x="-84141" y="244623" z="-3729" feeCount="9400" />
			<location name="Elven Village" x="46890" y="51531" z="-2976" feeCount="16000" />
			<location name="Dark Elf Village" x="9709" y="15566" z="-4568" feeCount="16000" />
			<location name="Dwarven Village" x="115120" y="-178224" z="-917" feeCount="38000" />
			<location name="Orc Village" x="-45186" y="-112459" z="-236" feeCount="26000" />
			<location name="Langk Lizardman Dwellings" x="-44763" y="203497" z="-3592" feeCount="1800" />
			<location name="Windmill Hill" x="-75437" y="168800" z="-3632" feeCount="550" />
			<location name="Fellmere Harvesting Grounds" x="-63736" y="101522" z="-3552" feeCount="1400" />
			<location name="Forgotten Temple" x="-53001" y="191425" z="-3568" feeCount="2000" />
			<location name="Orc Barracks" x="-89763" y="105359" z="-3576" feeCount="1800" />
			<location name="Windy Hill" x="-88539" y="83389" z="-2864" feeCount="2600" />
			<location name="Abandoned Camp" x="-49853" y="147089" z="-2784" feeCount="1200" />
			<location name="Wastelands" x="-16526" y="208032" z="-3664" feeCount="3400" />
			<location name="Red Rock Ridge" x="-42256" y="198333" z="-2800" feeCount="3700" />
		</teleport>
		<teleport type="NOBLES_TOKEN">
			<location name="Gludin Arena" x="-87328" y="142266" z="-3640" feeId="6651" feeCount="1" />
			<location name="Giran Arena" x="73579" y="142709" z="-3768" feeId="6651" feeCount="1" />
			<location name="Center of the Forgotten Temple" x="-54026" y="179504" z="-4650" feeId="6651" feeCount="1" />
			<location name="Wastelands, Western Region" x="-47506" y="179572" z="-3632" feeId="6651" feeCount="1" />
			<location name="Coliseum" x="146440" y="46723" z="-3400" feeId="6651" feeCount="1" />
		</teleport>
		<teleport type="NOBLES_ADENA">
			<location name="Gludin Arena" x="-87328" y="142266" z="-3640" feeCount="1000" />
			<location name="Giran Arena" x="73579" y="142709" z="-3768" feeCount="1000" />
			<location name="Center of the Forgotten Temple" x="-54026" y="179504" z="-4650" feeCount="1000" />
			<location name="Wastelands, Western Region" x="-47506" y="179572" z="-3632" feeCount="1000" />
			<location name="Coliseum" x="146440" y="46723" z="-3400" feeCount="1000" />
		</teleport>
	</npc>
</list>

=== Criticaldex/L2JLivingWorld/game/data/teleporters/town/30233.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/teleporterData.xsd">
	<npc id="30233"> <!-- Esmeralda -->
		<teleport type="NORMAL">
			<location name="Town of Aden" x="146705" y="25840" z="-2000" feeCount="5900" castleId="5" />
			<location name="Town of Oren" x="82956" y="53162" z="-1470" feeCount="4100" castleId="4" />
			<location name="Hardin's Private Academy" x="105846" y="109762" z="-3170" feeCount="3400" castleId="3" />
			<location name="Enchanted Valley, Southern Region" x="124904" y="61992" z="-3973" feeCount="1300" />
			<location name="Enchanted Valley, Northern Region" x="104426" y="33746" z="-3825" feeCount="3600" />
			<location name="Forest of Mirrors" x="142065" y="81300" z="-3000" feeCount="2000" />
		</teleport>
		<teleport type="NOBLES_TOKEN">
			<location name="Gludin Arena" x="-87328" y="142266" z="-3640" feeId="6651" feeCount="1" />
			<location name="Giran Arena" x="73579" y="142709" z="-3768" feeId="6651" feeCount="1" />
			<location name="The Center of the Forest of Mirrors" x="166080" y="75574" z="-2992" feeId="6651" feeCount="1" />
			<location name="The Center of the Enchanted Valley" x="114674" y="44150" z="-3376" feeId="6651" feeCount="1" />
			<location name="Hunters Valley" x="114306" y="86573" z="-3112" feeId="6651" feeCount="1" />
			<location name="Coliseum" x="146440" y="46723" z="-3400" feeId="6651" feeCount="1" />
		</teleport>
		<teleport type="NOBLES_ADENA">
			<location name="Gludin Arena" x="-87328" y="142266" z="-3640" feeCount="1000" />
			<location name="Giran Arena" x="73579" y="142709" z="-3768" feeCount="1000" />
			<location name="The Center of the Forest of Mirrors" x="166080" y="75574" z="-2992" feeCount="1000" />
			<location name="The Center of the Enchanted Valley" x="114674" y="44150" z="-3376" feeCount="1000" />
			<location name="Hunters Valley" x="114306" y="86573" z="-3112" feeCount="1000" />
			<location name="Coliseum" x="146440" y="46723" z="-3400" feeCount="1000" />
		</teleport>
	</npc>
</list>

=== Criticaldex/L2JLivingWorld/game/data/teleporters/town/31964.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/teleporterData.xsd">
	<npc id="31964"> <!-- Bilia -->
		<teleport type="NORMAL">
			<location name="Rune Township" x="43835" y="-47749" z="-792" feeCount="10000" castleId="8" />
			<location name="Town of Goddard" x="147596" y="-56294" z="-2776" feeCount="10000" castleId="7" />
			<location name="Town of Aden" x="146705" y="25840" z="-2000" feeCount="53000" castleId="5" />
			<location name="Town of Oren" x="83011" y="53207" z="-1470" feeCount="59000" castleId="4" />
			<location name="Heine" x="111455" y="219400" z="-3546" feeCount="100000" castleId="6" />
			<location name="The Town of Giran" x="83458" y="148012" z="-3400" feeCount="87000" castleId="3" />
			<location name="The Town of Dion" x="15671" y="142994" z="-2704" feeCount="88000" castleId="2" />
			<location name="The Town of Gludio" x="-12694" y="122776" z="-3114" feeCount="85000" castleId="1" />
			<location name="Orc Village" x="-45158" y="-112583" z="-236" feeCount="13000" />
			<location name="Dwarven Village" x="115120" y="-178224" z="-917" feeCount="4400" />
			<location name="Den of Evil" x="68693" y="-110438" z="-1904" feeCount="3000" />
			<location name="Plunderous Plains" x="111965" y="-154172" z="-1528" feeCount="1600" />
			<location name="Frozen Labyrinth" x="113903" y="-108752" z="-848" feeCount="3500" />
			<location name="Crypts of Disgrace" x="47692" y="-115745" z="-3744" feeCount="1900" />
			<location name="Pavel Ruins" x="91280" y="-117152" z="-3928" feeCount="2100" />
		</teleport>
		<teleport type="NOBLES_TOKEN">
			<location name="Gludin Arena" x="-87328" y="142266" z="-3640" feeId="6651" feeCount="1" />
			<location name="Giran Arena" x="73579" y="142709" z="-3768" feeId="6651" feeCount="1" />
			<location name="Frost Lake" x="107577" y="-122392" z="-3632" feeId="6651" feeCount="1" />
			<location name="Crypts of Disgrace" x="44221" y="-114232" z="-2784" feeId="6651" feeCount="1" />
			<location name="Sky Wagon Relic" x="121618" y="-141554" z="-1496" feeId="6651" feeCount="1" />
			<location name="Coliseum" x="146440" y="46723" z="-3400" feeId="6651" feeCount="1" />
		</teleport>
		<teleport type="NOBLES_ADENA">
			<location name="Gludin Arena" x="-87328" y="142266" z="-3640" feeCount="1000" />
			<location name="Giran Arena" x="73579" y="142709" z="-3768" feeCount="1000" />
			<location name="Frost Lake" x="107577" y="-122392" z="-3632" feeCount="1000" />
			<location name="Crypts of Disgrace" x="44221" y="-114232" z="-2784" feeCount="1000" />
			<location name="Sky Wagon Relic" x="121618" y="-141554" z="-1496" feeCount="1000" />
			<location name="Coliseum" x="146440" y="46723" z="-3400" feeCount="1000" />
		</teleport>
	</npc>
</list>

=== Criticaldex/L2JLivingWorld/game/data/teleporters/chamberlain/35555.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/teleporterData.xsd">
	<npc id="35555"> <!-- August -->
		<teleport type="OTHER">
			<location name="Front Of Schuttgart Castle" x="76358" y="-145548" z="-1176" />
			<location name="Schuttgart Town Square" x="87379" y="-142322" z="-1336" />
			<location name="Front of the Archaic Fortress" x="105007" y="-140874" z="-3360" />
			<location name="The Center of the Abandoned Coal Mines" x="144706" y="-173223" z="-1520" feeCount="500" />
			<location name="Plunderous Plains" x="111965" y="-154172" z="-1528" feeCount="500" />
			<location name="Den of Evil" x="68693" y="-110438" z="-1946" feeCount="500" />
			<location name="Ice Merchant Cabin" x="113903" y="-108752" z="-860" feeCount="500" />
			<location name="Crypts of Disgrace" x="47692" y="-115745" z="-3744" feeCount="500" />
		</teleport>
	</npc>
</list>

=== Criticaldex/L2JLivingWorld/game/data/teleporters/clanhall/Rune/35572.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/teleporterData.xsd">
	<npc id="35572"> <!-- Jimmy -->
		<teleport name="tel1" type="OTHER">
			<location name="Village Square" x="43889" y="-49101" z="-792" />
			<location name="South Gate Entrance" x="43307" y="-46563" z="-816" />
			<location name="North Gate Entrance" x="40909" y="-52670" z="-896" />
		</teleport>
		<teleport name="tel2" type="OTHER">
			<location name="Village Square" x="43889" y="-49101" z="-792" />
			<location name="South Gate Entrance" x="43307" y="-46563" z="-816" />
			<location name="North Gate Entrance" x="40909" y="-52670" z="-896" />
			<location name="Forest of the Dead" x="52107" y="-54328" z="-3158" feeCount="500" />
			<location name="Wild Beast Pastures" x="43805" y="-88010" z="-2780" feeCount="500" />
			<location name="Swamp of Screams" x="69340" y="-50203" z="-3314" feeCount="500" />
			<location name="Valley of Saints" x="65307" y="-71445" z="-3696" feeCount="500" />
			<location name="Monastery of Silence" x="106414" y="-87799" z="-2949" feeCount="500" />
			<location name="Shyeed's Cavern" x="76911" y="-55295" z="-5824" feeCount="500" />
		</teleport>
	</npc>
</list>

=== Criticaldex/L2JLivingWorld/game/data/teleporters/clanhall/Dion/35383.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/teleporterData.xsd">
	<npc id="35383"> <!-- Tamutak -->
		<teleport name="tel1" type="OTHER">
			<location name="Village Square" x="19025" y="145245" z="-3107" />
			<location name="East Gate Entrance" x="21511" y="145866" z="-3153" />
			<location name="North Gate Entrance" x="18891" y="142365" z="-3051" />
			<location name="South Gate Entrance" x="17394" y="147593" z="-3129" />
			<location name="West Gate Entrance" x="16582" y="144130" z="-2960" />
		</teleport>
		<teleport name="tel2" type="OTHER">
			<location name="Village Square" x="19025" y="145245" z="-3107" />
			<location name="East Gate Entrance" x="21511" y="145866" z="-3153" />
			<location name="North Gate Entrance" x="18891" y="142365" z="-3051" />
			<location name="South Gate Entrance" x="17394" y="147593" z="-3129" />
			<location name="West Gate Entrance" x="16582" y="144130" z="-2960" />
			<location name="Cruma Marshlands" x="5106" y="126916" z="-3664" feeCount="500" />
			<location name="Fortress of Resistance" x="47382" y="111278" z="-2104" feeCount="500" />
			<location name="Plains of Dion" x="630" y="179184" z="-3720" feeCount="500" />
			<location name="Tanor Canyon" x="60374" y="164301" z="-2856" feeCount="500" />
			<location name="Entrance to Floran Village" x="17430" y="170103" z="-3506" feeCount="500" />
		</teleport>
	</npc>
</list>
